# python file for the dictionary for RNA:ADT pairs for the ADT panel
import scanpy as sc
import pandas as pd

adata = sc.read_h5ad("/mnt/ibm_lg/yan")

RNA_ADT_dict = {"CD101":'CD101',
                "ITGAE":'CD103',
                "ENG":'CD105',
                "LAMP1":'CD107a',
                "NECTIN2":'CD112',
                "CSF1R":'CD115',
                "IFNGR1":'CD119',
                "ITGAL":'CD11a',
                "ITGAM":'CD11b',
                "ITGAX":'CD11c',
                "IL2RB":'CD122',
                "IL3RA":'CD123',
                "IL4R":'CD124',
                "IL7R":'CD127',
                "ANPEP":'CD13',
                "TNFRSF4":'CD134',
                "TNFRSF9":'CD137',
                "CD14":'CD14',
                "THBD": 'CD141',
                "F3":'CD142',
                "MCAM":'CD146',
                "CTLA4":'CD152',
                "CD40LG":'CD154',
                "PVR":'CD155',
                #"KIR2DL1":'CD158', # these CD158 genes don't exist in our transcriptome reference for some reason.
                #"KIR2DL2":'CD158b',
                #"KIR3DL1":'CD158e1',
                "FCGR3A":'CD16',
                "KLRB1":'CD161',
                "SELPLG":'CD162',
                "CD163":'CD163',
                "SIGLEC1":'CD169',
                "SIRPA":'CD172a',
                "ITGB2":'CD18',
                "CXCR5":'CD185',
                "CD19":'CD19',
                "CCR2":'CD192',
                "CCR4":'CD194',
                "CCR5":'CD195',
                "CCR6":'CD196',
                "CD1C":'CD1c',
                "CD1D":'CD1d',
                "CD2":'CD2',
                "MS4A1":'CD20',
                "CR2":'CD21',
                "CD22":'CD22',
                "LAG3":'CD223',
                "GGT1":'CD224',
                "CD226":'CD226',
                "FCER2":'CD23',
                "CD24":'CD24',
                "CD244":'CD244',
                "IL2RA":'CD25',
                "DPP4":'CD26',
                "TNFRSF13C":'CD268',
                "CD27":'CD27',
                "TNFRSF14":'CD270',
                "BTLA":'CD272',
                "CD274":'CD274',
                "ICOS":'CD278',
                "PDCD1":'CD279',
                "CD28":'CD28',
                "ITGB1":'CD29',
                "CD3E":'CD3',
                "CLEC4C":'CD303',
                "NRP1":'CD304',
                "PECAM1":'CD31',
                "KLRK1":'CD314',
                "SLAMF7":'CD319',
                "FCGR2A":'CD32',
                "SIGLEC7":'CD328',
                "CD33":'CD33',
                "NCR1":'CD335',
                "CR1":'CD35',
                "SLAMF6":'CD352',
                "CD36":'CD36',
                "CD38":'CD38',
                "ENTPD1":'CD39',
                "CD4":'CD4',
                "CD40":'CD40',
                "ITGA2B":'CD41',
                "GP1BA":'CD42b',
                "CD44":'CD44',
                "PTPRC":'CD45',
                #"":'CD45RA', # theese CD45RA and RO return PTPRC from the ncbi query
                #"":'CD45RO',
                "CD47":'CD47',
                "CD48":'CD48',
                "ITGA1":'CD49a',
                "ITGA2":'CD49b',
                "ITGA4":'CD49d',
                "ITGA6":'CD49f',
                "CD5":'CD5',
                "CD52":'CD52',
                "ICAM1":'CD54',
                "NCAM1":'CD56',
                "B3GAT1":'CD57',
                "CD58":'CD58',
                "SELL":'CD62L',
                #"SELL":'CD62P', # "SELL" appears for both CD62L and CD62P
                "CD63":'CD63',
                "FCGR1A":'CD64',
                "CD69":'CD69',
                "CD7":'CD7',
                "TFRC":'CD71',
                "CD72":'CD72',
                "NT5E":'CD73',
                "CD79B":'CD79b',
                "CD8A":'CD8',
                "CD81":'CD81',
                "CD82":'CD82',
                "CD83":'CD83',
                "LILRB1":'CD85j',
                "CD86":'CD86',
                "C5AR1":'CD88',
                "CD9":'CD9',
                "CD93":'CD93',
                "KLRD1":'CD94',
                "FAS":'CD95',
                "CX3CR1":'CX3CR1',
                "FCER1A":'FceRIa',
                #"HLA-A":'HLA-A-B-C', # we might need to add all "HLA-A", "HLA-B", and "HLA-C", but for now, we will just go with this one.
                "HLA-DRB1":'HLA-DR', # HLA seems to be a large complex, so need to revisit this
                "HLA-E":'HLA-E',
                "IGHD":'IgD',
                "IGHM":'IgM',
                "KLRG1":'KLRG1',
                "OLR1":'LOX-1',
                #"":'Podoplanin',
                "TARP":'TCR', # there seems to be other genes as well, since the TCR is 
                #"":'TCRVa7.2',
                #"":'TCRVd2',
                "TIGIT":'TIGIT',
                "ITGB7":'integrinB7'}